# Generated by Django 6.0.4 on 2026-07-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='estadosocio',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado'),
        ),
    ]
