# Generated by Django 6.0.4 on 2026-07-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_alter_socio_estadosocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='cedulaidentidadjugador',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
    ]
