# Generated by Django 6.0.4 on 2026-07-09 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_jugador_cedulaidentidadjugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='idsocio',
            field=models.ForeignKey(blank=True, db_column='idsocio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.socio', verbose_name='Socio Donante'),
        ),
    ]
