# Generated by Django 6.0.4 on 2026-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_regalo_idsocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaRecarga',
            fields=[
                ('idtarjetarecarga', models.AutoField(primary_key=True, serialize=False)),
                ('nombretarjetarecarga', models.CharField(max_length=100, verbose_name='Nombre del Paquete')),
                ('tiposaldo', models.CharField(choices=[('Efectivo', 'Saldo Real ($)'), ('Virtual', 'Fichas Virtuales')], max_length=20, verbose_name='Tipo de Saldo Destino')),
                ('montotarjetarecarga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad de Saldo/Puntos que Otorga')),
                ('preciodetarjetarecarga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta (Lo que paga el usuario)')),
                ('descripciontarjetarecarga', models.TextField(verbose_name='Beneficios (Separados por comas)')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=15)),
                ('espopular', models.BooleanField(default=False, verbose_name='¿Es la tarjeta más popular?')),
            ],
            options={
                'verbose_name': 'Tarjeta de Recarga',
                'verbose_name_plural': 'Tarjetas de Recarga',
                'db_table': 'TarjetaRecarga',
            },
        ),
    ]
