# Generated by Django 6.0.4 on 2026-07-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_tarjetarecarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionRecarga',
            fields=[
                ('idtransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total a Pagar')),
                ('saldo_acreditar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo/Puntos a Acreditar')),
                ('fechatransaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fechaactualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('metodopago', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pago')),
                ('referenciapago', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Transacción (Pasarela)')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='media/jugador/recargas/', verbose_name='Comprobante (Si es manual)')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Pago/Aprobación'), ('Completada', 'Completada y Saldo Acreditado'), ('Rechazada', 'Rechazada/Cancelada')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('idjugador', models.ForeignKey(db_column='idjugador', on_delete=django.db.models.deletion.CASCADE, to='bingo.jugador', verbose_name='Jugador Solicitante')),
                ('idtarjeta', models.ForeignKey(db_column='idtarjeta', on_delete=django.db.models.deletion.PROTECT, to='bingo.tarjetarecarga', verbose_name='Paquete Comprado')),
            ],
            options={
                'verbose_name': 'Transacción de Recarga',
                'verbose_name_plural': 'Historial de Transacciones',
                'db_table': 'TransaccionRecarga',
            },
        ),
    ]
