# Generated by Django 6.0.4 on 2026-07-09 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0006_transaccionrecarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='idpartida',
            field=models.ForeignKey(blank=True, db_column='idpartida', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.partidabingo', verbose_name='Sorteado en Ronda'),
        ),
    ]
