# Generated by Django 6.0.4 on 2026-07-10 02:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0007_regalo_idpartida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoracionSistema',
            fields=[
                ('idvaloracion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='Estrellas')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de Valoración')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Valoración del Sistema',
                'verbose_name_plural': 'Valoraciones del Sistema',
                'db_table': 'ValoracionSistema',
            },
        ),
    ]
