# Generated by Django 6.0.4 on 2026-07-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0008_valoracionsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataformajuego',
            name='logoplataforma',
            field=models.ImageField(blank=True, null=True, upload_to='media/web/plataforma/logos/', verbose_name='Logo de la Plataforma'),
        ),
        migrations.AlterField(
            model_name='regalo',
            name='urlimagen',
            field=models.ImageField(upload_to='media/socio/regalo/imagenes/', verbose_name='Imagen del Regalo'),
        ),
        migrations.AlterField(
            model_name='transaccionrecarga',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='media/jugador/Comprobante_recargas/', verbose_name='Comprobante (Si es manual)'),
        ),
    ]
