# Generated by Django 6.0.4 on 2026-07-13 20:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0009_alter_plataformajuego_logoplataforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='comprobanteahorro',
            field=models.FileField(blank=True, null=True, upload_to='media/socio/ahorro/comprobantes/', verbose_name='Comprobante de Ahorro'),
        ),
        migrations.AddField(
            model_name='ahorro',
            name='idmetodopago',
            field=models.ForeignKey(blank=True, db_column='idmetodopago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.metodopago', verbose_name='Cuenta de Destino'),
        ),
        migrations.AddField(
            model_name='aportesemanal',
            name='comprobanteaporte',
            field=models.FileField(blank=True, null=True, upload_to='media/socio/aportes/comprobantes/', verbose_name='Comprobante de Cuota Semanal'),
        ),
        migrations.AddField(
            model_name='aportesemanal',
            name='idmetodopago',
            field=models.ForeignKey(blank=True, db_column='idmetodopago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.metodopago', verbose_name='Cuenta de Destino'),
        ),
        migrations.AddField(
            model_name='aportesemanal',
            name='montoaporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto del Aporte'),
        ),
    ]
