# Generated by Django 6.0.4 on 2026-07-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0010_ahorro_comprobanteahorro_ahorro_idmetodopago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aportesemanal',
            name='idregalo',
        ),
    ]
