# Generated by Django 6.0.4 on 2026-07-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0011_remove_aportesemanal_idregalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportesemanal',
            name='estadoaporte',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente de Pago'), ('En Revision', 'En Revisión'), ('Al Dia', 'Al Día'), ('Atrasado', 'Atrasado')], max_length=20, null=True, verbose_name='Estado del Aporte'),
        ),
    ]
