# Generated by Django 6.0.4 on 2026-07-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0012_alter_aportesemanal_estadoaporte'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aportesemanal',
            name='chk_aportesemanal_estadoaporte',
        ),
        migrations.AddConstraint(
            model_name='aportesemanal',
            constraint=models.CheckConstraint(condition=models.Q(('estadoaporte__in', ['Pendiente', 'En Revision', 'Al Dia', 'Atrasado'])), name='chk_aportesemanal_estadoaporte'),
        ),
    ]
