# Generated by Django 6.0.4 on 2026-07-15 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0013_remove_aportesemanal_chk_aportesemanal_estadoaporte_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aportesemanal',
            name='chk_aportesemanal_metodoingreso',
        ),
        migrations.AddField(
            model_name='ahorro',
            name='origenahorro',
            field=models.CharField(blank=True, default='Directo', max_length=50, null=True, verbose_name='Origen del Ahorro'),
        ),
        migrations.AddField(
            model_name='aportesemanal',
            name='idregalo',
            field=models.ForeignKey(blank=True, db_column='idregalo', null=True, on_delete=django.db.models.deletion.CASCADE, to='bingo.regalo', verbose_name='Regalo Asignado'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='comprobanteahorro',
            field=models.FileField(blank=True, null=True, upload_to='ahorro/comprobantes/', verbose_name='Comprobante de Ahorro'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='estadoahorro',
            field=models.CharField(choices=[('Acreditado', 'Acreditado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=25, verbose_name='Estado del Ahorro'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='idbingo',
            field=models.ForeignKey(blank=True, db_column='idbingo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.bingo', verbose_name='Bingo Asociado'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='montoahorro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Ahorrado'),
        ),
        migrations.AlterField(
            model_name='aportesemanal',
            name='comprobanteaporte',
            field=models.FileField(blank=True, null=True, upload_to='aportes/comprobantes/', verbose_name='Comprobante de Cuota Semanal'),
        ),
        migrations.AlterField(
            model_name='aportesemanal',
            name='metodoingreso',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Fisico', 'Físico')], max_length=50, null=True, verbose_name='Método de Ingreso'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobantepago',
            field=models.FileField(max_length=255, upload_to='pago/comprobantes_pagos/', verbose_name='Archivo del Comprobante'),
        ),
        migrations.AddConstraint(
            model_name='aportesemanal',
            constraint=models.CheckConstraint(condition=models.Q(('metodoingreso__in', ['Efectivo', 'Transferencia', 'Fisico']), ('metodoingreso__isnull', True), _connector='OR'), name='chk_aportesemanal_metodoingreso'),
        ),
    ]
