# Generated by Django 6.0.4 on 2026-07-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0014_remove_aportesemanal_chk_aportesemanal_metodoingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='comprobanteahorro',
            field=models.FileField(blank=True, null=True, upload_to='media/ahorro/comprobantes/', verbose_name='Comprobante de Ahorro'),
        ),
        migrations.AlterField(
            model_name='aportesemanal',
            name='comprobanteaporte',
            field=models.FileField(blank=True, null=True, upload_to='media/aportes/comprobantes/', verbose_name='Comprobante de Cuota Semanal'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobantepago',
            field=models.FileField(max_length=255, upload_to='media/pago/comprobantes_pagos/', verbose_name='Archivo del Comprobante'),
        ),
    ]
