# Generated by Django 6.0.4 on 2026-07-20 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0015_alter_ahorro_comprobanteahorro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='idcuentadestino',
            field=models.ForeignKey(blank=True, db_column='idcuentadestino', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.cuentabancaria', verbose_name='Cuenta para desembolso'),
        ),
    ]
