# Generated by Django 6.0.4 on 2026-07-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0017_alter_prestamo_estadoprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estadoprestamo',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Aprobado', 'Aprobado'), ('En Curso', 'En Curso (Pagando)'), ('Liquidado', 'Liquidado')], default='Solicitado', max_length=20, verbose_name='Estado del Préstamo'),
        ),
    ]
