# Generated by Django 6.0.4 on 2026-07-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0018_alter_prestamo_estadoprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='estadoahorro',
            field=models.CharField(choices=[('Acreditado', 'Acreditado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Retirar', 'Retirar'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=25, verbose_name='Estado del Ahorro'),
        ),
    ]
