# Generated by Django 6.0.4 on 2026-07-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0019_alter_ahorro_estadoahorro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='estadobingo',
            field=models.CharField(choices=[('Programado (Oculto)', 'Programado (Oculto)'), ('Programado', 'Programado'), ('En Curso', 'En Curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=20, verbose_name='Estado del Bingo'),
        ),
    ]
