# Generated by Django 6.0.4 on 2026-07-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0020_alter_bingo_estadobingo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='comprobantedesembolso',
            field=models.FileField(blank=True, null=True, upload_to='media/prestamo/comprobantes_desembolso/', verbose_name='Comprobante de Desembolso'),
        ),
    ]
