# Generated by Django 6.0.4 on 2026-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0021_prestamo_comprobantedesembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, verbose_name='Recordatorio 30m Enviado'),
        ),
    ]
